# Generated by Django 4.2.3 on 2023-08-19 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FL', 'Fruits et légumes'), ('VP', 'Viande et poisson'), ('LT', 'Laitages'), ('PB', 'Pain et boulangerie'), ('CO', 'Céréales et œufs'), ('BS', 'Boissons'), ('PE', "Produits d'épicerie")], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('basse guinee', 'Basse Guinée'), ('moyenne guinee', 'Moyenne Guinée'), ('haute guinee', 'Haute Guinée'), ("guinee n'zerekore", "Guinée N'Zérékoré")], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
